### ISSUE TITLE
A question about Arm core Neoverse V1  - "mix code freely"

### ISSUE THREAD

**Issue by docularxu** [AshokBhat/notes#1]
Hi, Ashok

May I ask you a question? In the material on this [link](https://www.anandtech.com/show/16073/arm-announces-neoverse-v1-n2), there is a quote in one of the slides "With SVE developers can **mix code freely** between narrow and wide vector execution”.

Do you know what exactly "mix code freely" means? I don't think it is VLA Programming cause it is not using that word. Then what is it? :)

I learned from your Wiki that V1 has 2*256-bit pipelines. Does this has any relationship with "mix code freely"? How a developer can take advantage of two 256b SVE pipelines?

Thank you very much.
BR,
Guodong Xu

**Comment by AshokBhat** [comment]
TBH I am not sure what that really means. All I can say is that VLA makes it possible to run it on any vector width, whether it is 256 or 512 or 128-bit. You do not have to rewrite/recompile your code. 

Multiple SVE pipelines can be taken advantage of by the compiler by using aggressive unrolling so that there are two independent SVE instructions that can be executed at the same time.
